// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv


import "dotenv/config";
import { defineConfig } from "prisma/config";
import { PrismaNeon } from "@prisma/adapter-neon";

export default defineConfig({
  earlyAccess: true,
  schema: "prisma/schema.prisma",
  migrate: {
    adapter: () => {
      return new PrismaNeon({
        connectionString: process.env.DATABASE_URL!,
      });
    },
  },
});