import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider"
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
         <ClerkProvider >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          {/*header*/}
          <Header/>
          <main className="min-h-screen">
            {children}
          </main>
          <footer className="bg-muted/50 py-14 mt-3">
            <p className="flex flex-col justify-center items-center">Made with ❤️ by Next.Js</p>
          </footer>
          {/*footer*/}
        
        </ThemeProvider>
        </ClerkProvider>
        
        </body>
    </html>
  );
}
