"use server";

import { prisma } from "@/lib/prisma";
import { auth } from "@clerk/nextjs/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { err } from "inngest/types";


 const genAI=new GoogleGenerativeAI(process.env.GEMINI_API_KEY)
        const model=genAI.getGenerativeModel({
            model: "gemini-2.5-flash",
        })

export async function generateQuiz() {
     //!Check for userId of Clerk in prisma
        const {userId}=await auth();
        if(!userId){
            throw new Error("User Not Authorised")
        }
        const user = await prisma.user.findUnique({
        where: { clerkUserId: userId },
        select:{
            industry:true,
            skills:true,
        },
        });
    
        if(!user){
            throw new Error("User Not Found");
        }

        try{
const prompt

//! AI Generates the quiz asper the described response format 
= `
    Generate 10 technical interview questions for a ${
      user.industry
    } professional${
    user.skills?.length ? ` with expertise in ${user.skills.join(", ")}` : ""
  }.
    
    Each question should be multiple choice with 4 options.
    
    Return the response in this JSON format only, no additional text:
    {
      "questions": [
        {
          "question": "string",
          "options": ["string", "string", "string", "string"],
          "correctAnswer": "string",
          "explanation": "string"
        }
      ]
    }
  `;

    const result =await model.generateContent(prompt)
    const response=result.response
    const text=response.text();
    const cleanedText = text.replace(/```(?:json)?\n?/g, "").trim();
    const quiz=JSON.parse(cleanedText);
    return quiz.questions;
}
catch(error){
    console.log("Error Generating quiz: ",error);
    throw new Error("Failed to generate quiz questions");   
} 
}




export async function saveQuizResult(questions,answers,score){
     //!AI Questions will be sent to the frontend, The answers selected tracked by frotend,score calculated in frontend 
     //! SO they Given as the parameters
        let improvementTip=null;
        let wrongQuestionsText = "";
         //!Check for userId of Clerk in prisma
        const {userId}=await auth();
        if(!userId){
            throw new Error("User Not Authorised")
        }
        const user = await prisma.user.findUnique({
        where: { clerkUserId: userId },
        select:{
            id:true,
            industry:true,
            skills:true,
        },
        });
    
        if(!user){
            throw new Error("User Not Found");
        }

        
        //! Merge AI-generated questions with user responses
        //! and determine whether each answer is correct    
        const questionResults = questions.map((q,index)=>({
            //! q is the each question JSON generated by the AI that contains options,
            // !along with correct answer,explanation where questions are the AI generated questions sent back by frontend
            question:q.question,
            answer:q.correctAnswer,
            userAnswer:answers[index],
            isCorrect: q.correctAnswer===answers[index],
            explanation:q.explanation

            //! This is the Array we will be saving to our
            // ! Assessment Table of our database which combine AI question data with user answers

            //!  Saving the Quiz Result of the User
            //! Structure matches the Assessment.questions Json[] field
            //! Each object stores:
            //! question, correct answer, user's answer, correctness, explanation
        // ! questions     Json[]    // Array of {question, answer, userAnswer, isCorrect}


        }));

        
        //! Generating Improvement Tip for the Wrong Answers

        const wrongAnswers = questionResults.filter(
            (q)=>!q.isCorrect) //!Tracking the wrongly selected questions by user
        

        //!To give for the GEMINI PROMPT, we are preparing the following
         if(wrongAnswers.length > 0){
            wrongQuestionsText = wrongAnswers.map((q)=>
            `Question: "${q.question}"\nCorrect Answer: "${q.answer}"\nUser Answer: "${q.userAnswer}"`).join("\n\n");
         }

        
    const improvementPrompt = `
      The user got the following ${user.industry} technical interview questions wrong:

      ${wrongQuestionsText}

      Based on these mistakes, provide a concise, specific improvement tip.
      Focus on the knowledge gaps revealed by these wrong answers.
      Keep the response under 2 sentences and make it encouraging.
      Don't explicitly mention the mistakes, instead focus on what to learn/practice.
    `;

     try {
    const result =await model.generateContent(improvementPrompt)
    const response=result.response
    improvementTip=response.text().trim();
      
        
     } catch (error) {
        console.error("Error Generating Improvement Tip: ",error);
     }

    //! Saving the data to the Assessment Table 
     try {
        const assessment = await prisma.assessment.create({
            data:{
                userId:user.id,
                quizScore: score,
                questions:questionResults,
                category:"Technical",
                improvementTip,
            }
        }); 
        return assessment; //!Returning the Saved Record(or) Row Of the Assessment......
        
     } catch (error) {
        console.error("Error saving quiz result:",error);
        throw new Error("Failed to save quiz result");
        
     }




    }

export async function getAssessments(){
     //!Check for userId of Clerk in prisma
     //! Number of Assessment Records in Database = Number of Assessments Taken by the User
     //! So Fetching All Those Records......
        const {userId}=await auth();
        if(!userId){
            throw new Error("User Not Authorised")
        }
        const user = await prisma.user.findUnique({
        where: { clerkUserId: userId },
        select:{
            industry:true,
            skills:true,
        },
        });
    
        if(!user){
            throw new Error("User Not Found");
        }

        try {
            const assessments = await prisma.assessment.findMany({
                where:{
                    userId:user.id,
                },
                orderBy:{
                    createdAt:"asc",
                },
            });
            return assessments;
            
        } catch (error) {
            console.error("Error fetching assessments: ",error);
            throw new Error("Failed to fetch assessments");                      
        }
}